# Generated by Django 2.2.2 on 2019-09-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_message', models.CharField(blank=True, max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=30)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('group', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('register', models.BooleanField()),
            ],
        ),
    ]
